project:
  type: manuscript

execute:
  freeze: auto

format:
  elsevier-pdf:
    echo: false
    keep-tex: true
    keep-ipynb: true
    journal:
      name: Journal of the Acoustical Society of America
      formatting: preprint
      model: 3p
      cite-style: authoryear
    # include-in-header:
    #   text: |
    #     \usepackage{lineno}
    #     \linenumbers
  # docx:
  #   reference-doc: apaquarto.docx
  #   number-sections: true
  # qtypst-arkheion-typst:
  #   keep-typ: true
  #   suppress-bibliography: true
  #   bib-file: "FellowshipRefs-biblatex.bib"
bibliography: FellowshipRefs-biblatex.bib


