project:
  # type: manuscript
  title: "Soundscape Perception Indices (SPI)"

execute:
  freeze: auto

format:
  elsevier-pdf:
    echo: false
    keep-tex: true
    keep-ipynb: true
    journal:
      name: Journal of the Acoustical Society of America
      formatting: preprint
      model: 3p
      cite-style: authoryear
    # include-in-header:
    #   text: |
    #     \usepackage{lineno}
    #     \linenumbers
  # docx:
  #   reference-doc: apaquarto.docx
  #   number-sections: true
  # qtypst-arkheion-typst:
  #   keep-typ: true
  #   suppress-bibliography: true
  #   bib-file: "FellowshipRefs-biblatex.bib"
    html:
    toc: true
    toc-expand: 3
    theme: flatly
    number-sections: true
    code-fold: show
    page-layout: full
    embed-resources: true
bibliography: FellowshipRefs-biblatex.bib


