[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Andrew Mitchell", email = "andrew.mitchell.18@ucl.ac.uk"},
]
dependencies = [
    "soundscapy>=0.5.3",
    "jupyter>=1.0.0",
    "ipykernel>=6.28.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

