---
title: SPI - Defining bespoke and archetypal context-dependent Soundscape Perception Indices
author:
  - name: Andrew Mitchell
    email: andrew.mitchell.18@ucl.ac.uk
    affiliations: 
        - id: ucl-iede
          name: University College London
          department: Institute for Environmental Design & Engineering
    attributes:
        corresponding: true
  - name: Francesco Aletta
    email: f.aletta@ucl.ac.uk
    affiliations:
        - ref: ucl-iede
  - name: Tin Oberman
    email: t.oberman@ucl.ac.uk
    affiliations:
        - ref: ucl-iede
  - name: Jian Kang
    email: j.kang@ucl.ac.uk
    affilations:
        - ref: ucl-iede
abstract: |
    The soundscape approach provides a basis for considering the holistic perception of sound environments, in context. While steady advancements have been made in methods for assessment and analysis, a gap exists for comparing soundscapes and quantifying improvements in the multi-dimensional perception of a soundscape. To this end, there is a need for the creation of single value indices to compare soundscape quality which incorporate context, aural diversity, and specific design goals for a given application. Just as a variety of decibel-based indices have been developed for various purposes (e.g. LAeq, LCeq, L90, Lden, etc.), the soundscape approach requires the ability to create novel indices for different uses, but which share a common language and understanding. We therefore propose a unified framework for creating both bespoke and standardised single index measures of soundscape perception based on the soundscape circumplex model, allowing for new metrics to be defined in the future. The implementation of this framework is demonstrated through the creation of a public spaced typology-based index using data collected under the SSID Protocol, which was designed specifically for the purpose of defining soundscape indices. Indices developed under this framework can enable a broader and more efficient application of the soundscape approach.
keywords: 
  - keyword1
  - keyword2
date: last-modified
bibliography: FellowshipRefs-biblatex.bib

---

# Introduction

The EU Green Paper on Future Noise Policy indicates that 80 million EU citizens are suffering from unacceptable environmental noise levels , according to the WHO recommendation [@Berglund1999Guidelines] and the social cost of transport noise is 0.2-2% of total GDP. The publication of the EU Directive Relating to the Assessment and Management of Environmental Noise (END) [@EuropeanUnion2002Directive] in 2002 has led to major actions across Europe, with reducing noise levels as the focus, for which billions of Euros are being spent. However, it is widely recognised that only reducing sound level is not always feasible or cost-effective, and more importantly, with only ~30% of environmental noise annoyance depending on facets of parameters such as acoustic energy [@Guski1997Psychological], sound level reduction will not necessarily lead to improved quality of life.

Soundscape creation, separate from noise control engineering, is about the relationships between human physiology, perception, the sound environment, and its social/cultural context [@Kang2006Urban]. Soundscape research represents a paradigm shift in that it combines physical, social, and psychological approaches and considers environmental sounds as a 'resource' rather than 'waste' [@Kang2016Soundscape] relating to perceptual constructs rather than just physical phenomena. However, the current research is still at the stage of describing and identifying the problems and tends to be fragmented and focussed on only special cases e.g. subjective evaluations of soundscapes for residential areas [@SchulteFortkamp2013Introduction]. In the movement from noise control to soundscape creation [@Aletta2015Soundscape], a vital step is the standardisation of methods to assess soundscape quality.

<!-- TODO: Should rephrase the following paragraphs -->

The Decibel (dB) is the earliest and most commonly used scientific index measuring sound level. To represent the overall level of sound with a single value on one scale, as the Decibel index does, is often desirable. For this purpose, a number of different values representing sounds at various frequencies must be combined. Several frequency weighting networks have been developed since the 1930s, considering typical human responses to sound based on equal-loudness-level contours [@viii] and, among them, the A-weighting network, with resultant decibel values called dBA, has been commonly used in almost all the national/international regulations [@ix]. However, there have been numerous criticisms on its effectiveness [@x] as the correlations between dBA and perceived sound quality (e.g. noise annoyance) are often low [@xi].

Another set of indices is psychoacoustic magnitudes, including loudness, fluctuation strength or roughness, sharpness, and pitch strength, development with sound quality studies of industrial products since the 1980's [@xii]. These emerged when it was conceived that acoustic emissions had further characteristics than just level [@ciii]. But while psychoacoustic magnitudes have been proved to be successful for the assessment of product sound quality [@xiv], in the field of environmental acoustics, their applicability has been limited [@xv], since a significant feature of environmental acoustics is that there are multiple/dynamic sound sources.

Attendant with the transition from a noise reduction to soundscape paradigm is an urgent need for developing appropriate indices for soundscape, rather than continuously using dBA [@xvi]. 

## The need for Soundscape Indices

<!-- From Thesis -->

Soundscape studies strive to understand the perception of a sound environment, in context, including acoustic, (non-acoustic) environmental, contextual, and personal factors. These factors combine together to form a person's soundscape perception in complex interacting ways [@Berglund2006Soundscape]. Humans and soundscapes have a dynamic bidirectional relationship - while humans and their behaviour directly influence their soundscape, humans and their behaviour are in turn influenced by their soundscape [@Erfanian2019Psychophysiological]. 

When applied to urban sound and specifically to noise pollution, the soundscape approach introduces three key considerations beyond traditional noise control methods:

1. considering all aspects of the environment which may influence perception, not just the sound level and spectral content;
2. an increased and integrated consideration of the varying impacts which different sound sources and sonic characteristics have on perception; and
3. a consideration of both the positive and negative dimensions of soundscape perception.

This approach can enable better outcomes by identifying positive soundscapes (in line with the END's mandate to `preserve environmental noise quality where it is good' [@EuropeanUnion2002Directive]), better identify specific sources of noise which impact soundscape quality and pinpoint the characteristics which may need to be decreased, and illuminate alternative methods which could be introduced to improve a soundscape where a reduction of noise is impractical [@Fiebig2018Does; @Kang2018Impact]. These can all lead to more opportunities to truly improve a space by identifying the causes of positive soundscapes, while also potentially decreasing the costs of noise mitigation by offering more targeted techniques and alternative approaches.

The traditional focus on noise levels alone fails to capture the complexity of soundscape perception, which encompasses a multitude of factors beyond mere sound pressure levels. Factors such as the presence of natural or human-made sounds, their temporal patterns, and the overall contextual meaning ascribed to these sounds all contribute to the holistic perception of a soundscape. Consequently, there is a pressing need for the development of robust indices that can encapsulate this multi-dimensional nature of soundscape perception, enabling comparative evaluations and informing targeted interventions to enhance the overall quality of acoustic environments [@Chen2024Interventions]. 

<!-- End Thesis -->

Across both the visual and the auditory domain, research has suggested that a disconnect exists between the physical metrics used to describe urban environments and how they are perceived [@Kruize2019Exploring; @Yang2005Acoustic]. In addition, this disconnect can be extended further into how these environments influence the health and well-being of their users. To gain a better understanding of these spaces and their immpacts on people who work and live in cities, we must create assessment methods and metrics which go beyond merely characterising the physical environment and instead translate through the user's perception [@Mitchell2022Predictive].

## Note on Terminology

Before delving into the core discussion, it is crucial to establish a clear understanding of the terminology employed in the realm of soundscape evaluation. 

<!-- From Thesis -->

The soundscape community is undergoing a period of increased methodological standardization in order to better coordinate and communicate the findings of the field. This process has resulted in many operational tools designed to assess and understand how sound environments are perceived and apply this to shape modern noise control engineering approaches. Important topics which have been identified throughout this process are soundscape 'descriptors', 'indicators', and 'indices'. @Aletta2016Soundscape defined soundscape descriptors as 'measures of how people perceive the acoustic environment' and soundscape indicators as 'measures used to predict the value of a soundscape descriptor'. Soundscape indices can then be defined as 'single value scales derived from either descriptors or indicators that allow for comparison across soundscapes' [@Kang2019Towards].

<!-- End Thesis -->

Soundscape indicators refer to measurable aspects or attributes of a soundscape, such as loudness, tonal characteristics, or spectral content, which can be quantified through objective measurements or signal processing techniques. In contrast, soundscape descriptors are qualitative representations of the perceived characteristics of a soundscape, often derived from listener evaluations, subjective assessments, or semantic differential scales [@ISO12913Part2]. 

Indices, the primary focus of this article, are single numerical values that combine multiple indicators or descriptors to provide a comprehensive representation of the overall soundscape perception. These indices serve as powerful tools for quantifying and comparing soundscapes, enabling decision-makers and stakeholders to assess the impact of interventions, monitor changes over time, and prioritize areas for improvement.

[@Grinfeder2022What]

## Existing 'Soundscape Indices'

While the field of soundscape research has witnessed substantial progress, the development of standardized indices for evaluating and comparing soundscapes across diverse contexts has been relatively limited. Existing indices can be broadly seen as arising from two domains: soundscape ecology and soundscape perception. It is worth reviewing these indices to highlight how the framework proposed here is fundamentally different in both concept and aim.

### Soundscape Ecology

Within the realm of soundscape ecology, indices such as the Acoustic Diversity Index (ADI) and Frequency-dependenty Acoustic Diversity Index (FADI) [@Xu2023frequency] have been developed to quantify the diversity and complexity of acoustic signals within a given soundscape. These indices are particularly useful in ecological studies, providing insights into the richness and diversity of biophonic (natural) and anthrophonic (human-made) sound sources.

<mark>***Add additional information on ADI, FADI, NDSI, etc.***</mark>

However, while these indices contribute valuable insights into the ecological aspects of soundscapes, they do not directly address the perceptual dimensions that are central to the soundscape approach [@SchulteFortkamp2023Soundscapes]. The multi-dimensional nature of soundscape perception, encompassing factors such as pleasantness, eventfulness, and familiarity, necessitates a more comprehensive and context-sensitive approach.

### Soundscape Perception

In the domain of soundscape perception, the Green Soundscape Index (GSI) [@Kogan2018Green] has emerged as a notable attempt to quantify the perceived quality of soundscapes, particularly in urban environments. This index incorporates factors such as the presence and levels of natural sounds, human-made sounds, and their respective contributions to the overall soundscape perception.

The GSI is the ratio of the perceived extent of natural sounds (PNS) to the perceived extent of traffic noise (PTN):

$$
GSI = \frac{<PNS>}{<PTN>}
$$

The GSI is noted to range between 1/5 and 5, with several ranges of values given which correspond to general categories of the perceived dominance of traffic noise.

While GSI represents a commendable effort to bridge the gap between objective measurements and subjective perceptions, it remains limited in its ability to capture the full complexity of soundscape perception across diverse contexts. The intricate interplay between various sound sources, their temporal patterns, and the specific context in which they are experienced necessitates a more flexible and adaptable approach to index development.

## Motivations & Goals

The primary motivation behind the development of the Soundscape Perception Indices (SPIs) framework stems from the need to address the existing gap in quantifying and comparing soundscape quality across diverse contexts and applications. By creating a unified framework for defining these indices, the aim is to facilitate a broader and more efficient application of the soundscape approach in various domains, such as urban planning, environmental management, acoustic design, and policy development. 

The overarching aim of this framework is to empower stakeholders, decision-makers, and researchers with the ability to create tailored indices that align with their specific objectives and design goals, while simultaneously enabling cross-comparisons and benchmarking against empirically-defined soundscape archetypes. This dual approach not only acknowledges the context-dependent nature of soundscape perception but also fosters a common language and understanding, facilitating knowledge sharing and collaborative efforts within the field. 

*Ranking* - The ability to rank soundscapes based on their quality is a key goal of the SPI framework. This ranking can be used to compare soundscapes across different contexts, identify areas for improvement, and prioritize interventions accordingly.

*Standardisation* - The SPI framework aims to provide a standardized approach for defining and calculating soundscape indices, ensuring consistency and comparability across different applications and domains. This standardization enables the development of best practices and facilitates knowledge exchange within the field.

# Methodology

## Soundscape Circumplex & Projection

SPI is grounded in the soundscape circumplex model [@Axelsson2010principal; @Axelsson2012Swedish], a robust theoretical foundation for understanding and representing the multi-dimensional nature of soundscape perception. The reason for grounding the SPI into the soundscape circumplex is that we have observed this model (and its corresponding PAQs) to become the most prevalent one in soundscape literature [@Aletta2023Adoption]. For the sake of supporting standardization, we feel that we need the SPI to align to this model.

<!-- From Thesis -->

Method A is built on a series of descriptors referred to as the Perceived Affective Quality (PAQ), proposed by [@Ax/elsson2010principal]. These PAQs are based on the pleasantness-activity paradigm present in research on emotions and environmental psychology, in particular Russell's circumplex model of affect [@Russell1980circumplex]. As summarised by Axelsson: "Russell's model identifies two dimensions related to the perceived pleasantness of environments and how activating or arousing the environment is."

To move the 8-item PAQ responses into the 2-dimensional circumplex space, we use the projection method first presented in ISO 12913-3:2018. This projection method and its associated formulae were recently updated further in @Aletta2024 to include a correction for the language in which the survey was conducted. The formulae are as follows:

$$
P_{ISO} = \frac{1}{\lambda_{pl}} \sum_{i=1}^{8} \cos \theta_i \cdot \sigma_i
$$

$$
E_{ISO} = \frac{1}{\lambda_{pl}} \sum_{i=1}^{8} \sin \theta_i \cdot \sigma_i 
$$

where $\text{PAQ}_i\$ is the response to the \(i\)th item of the PAQ. The resulting \(x\) and \(y\) values are then used to calculate the polar angle \(\theta\) and the radial distance \(r\) as follows:

<mark>***Add formulae for $\theta$ and r***</mark>

Using the angles derived in @Aletta2024, the following table is used to convert the angles into the ISO 12913-3:2018 circumplex space:
